export const configEnv = () => {
	return {
		NODE_ENV: process.env.NODE_ENV ? process.env.NODE_ENV : 'development',
		PORT: process.env.PORT ? process.env.PORT : 4000,
		MONGODB_URL: process.env.MONGODB_URL ? process.env.MONGODB_URL : '', 
		DB_NAME: process.env.DB_NAME ? process.env.DB_NAME : 'LOGIN_DB',
		SECRET_KEY: process.env.SECRET_KEY ? process.env.SECRET_KEY : 'pawa',
		TOKEN_EXP: process.env.TOKEN_EXP ? process.env.TOKEN_EXP : 3600,
		FIREBASE_CERT:process.env.FIREBASE_CERT ? process.env.FIREBASE_CERT : '{			"type": "service_account",			"project_id": lomba",			"private_key_id": c586a",			"private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDLEr3JjtZ7A9r6\nZ6p9fn9h3OJan+bDOCxTA60PlFWopEJcPao6JTXEmdvVwV80EYfodL2GMzuf/adu\njN2E2lGmPrfooPcYSNIZ9SpcRiD+N9GftJFENTzfRQJBliWOYtAszZzCESQXSFLj\n0RPTyjGLdyuF6awCHqTLvFn1BzC77L65fp5ZffZaQkEN3i4feo69ChVbioqLpuXd\nnNBO3aEra/yinNuV4NXJbKxinah0Fc1VKISvXLp7vLahYfbkpMxqeDGo3qjSzWd/\nP/LD8fmBC/IoUHUfCT6ZBSxZlrWlTp6UIerMnYPsfXqBcAdce1Pv71qWuSWwuoeG\nUPm7Q18VAgMBAAECggEACde8NC9ErQy4SefJZzDA6tTiccMLU83+s/1bH4SwjC59\n+uuQOyY/j2pnsdogC62H2VgDMaR9ENmiCmUwfXZ5e6XRkyhuIZKyAEkWRwetJLU+\n509AtT4hV68IF3a4FkkqzukeXnenOKusPNeO7vZ/ZUOe6+wyBp5GnYthDtPM5GbU\niupgafyHCPg8ykrPCKojRzH3IjXCjwkuqm/yFATDr/AzJ9FbICkLbVzKNyAVT2oa\nwYhIoy1RmLYB9nq5MWkRoo3in0FmCtLzejIAt3kpYAuHfU9sNuLctj4WU1i05jir\n7YWsJ80/2Z/izSB8B52GtdZjrsSaKzFFe07i/NJkQQKBgQDw3JIeienWcu4GF/Ig\nwMUiM7jTKDfvX98JfV+aFgXFJMcuooad4NjrtSsjro6QMjPqZvX+vbkcE7TLFUxu\nf7ZHipRd9eaeU03gxnZubvn5p5hsHDUft4+eTCy1R1OJoclia4+Xylgj5XPdXUW9\n/lRxWFc8xOx2jdEhC80Y5QA79QKBgQDX1ikeOaRnBrKVGagWRwqImIeXXzaozrfO\ni3e4YXljpUxEWRmCc2AI1RhDw4yAOJS0vYRFHGWKf285j6fLCG50dtY7prefxsg8\ncdPhS+l2/OELj4TTi7w6ON/+tnc25kKIgO61X5BQM4unnf886IYJsLDGpZJr29Wk\nKkvsdzbCoQKBgQCoS3ZNoE+jZ+qol1K3T/puS3V5FUEAIRzWpKOIJpshhPEnxKgK\n6HCpQY1DAVTbrDhaMFbyB96vn5VT0S32h4X1tv60KH1bYxmnVQSrZR+FMXVvFMaJ\nwti24sLaZ1wXbtQn0MAkb13mtwyeP+3bMzoNeIx8CZyvuafGT1ifbGMdgQKBgFSB\nEeo2kUqREbxUpj3KpLIkXfoDGkhvXwGsEzyKVVeRMVIVPGqZt4DdxblKR6kv/fDh\nvna8jnjyOd7kgsJ4U56fpHMIbB5PWrhnrJgp+4dNrOK010FoFVMKT5DPac+ByYze\nRheXCc6Mz+HZd0QmmcwTdLLhwnkeQgAbW0yCxFrhAoGBAN2/3VTkjAnqYoM5LFoK\nDyNrLM5p/zydzzLm7MBgFNeVaUWel6GBv/kVKICq34uxBzpILfir9GO18BGqd1pp\nU1K0yq5iUDEVJ+0KbLWkozFZmuswya/YZHrKW4fe+Z4ElX1ghi+UBpFDcUSYj9vf\n4HufOtTTmVt9KUTaor+MR6fd\n-----END PRIVATE KEY-----\n",			"client_email": "firebase-adminsdk-8hixu@lomba.iam.gserviceaccount.com",			"client_id": "1132",			"auth_uri": "https://accounts.google.com/o/oauth2/auth",			"token_uri": "https://oauth2.googleapis.com/token",			"auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",			"client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-8hixu%40lomba.iam.gserviceaccount.com"		  }'
	};
};